name: molcv
channels:
    - conda-forge
    - defaults
dependencies:
    - python>=3.7
    - sphinx==1.8.5
    - sphinx_rtd_theme
    - scikit-learn==1.0.2
    - setuptools
    - pytorch==1.10
    - numpy>=1.20.0
    - pandas
    - tqdm
    - tensorboardX
    - cv2
    - matplotlib
    - pyyaml
    - pip>=21.1
    - mdanalysis==2.0.0
    - opencv-contrib-python==4.5.5
